title: Huong Nguyen
author: Huong Nguyen
email: huong@iastate.edu
description: > # this means to ignore newlines until "baseurl:"
A website where I talk about weeds

# social links
#twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  hnguyen19 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
